version: '3.8'

services:
  nonfungibletables:
    image: l3m0n42/nonfungibletwobles:latest
    container_name: nonfungibletables
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped
    volumes:
      - nft:/KeyboardKowboys/

volumes:
  nft:
    name: nft