- name: Install WinPEAS to Windows
  hosts: windows_servers
  gather_facts: false
  
  vars:
    ad_domain: "bobby.shmurda"  # Specify your Active Directory domain
    ad_user: "Administrator"     # Specify a user with sufficient privileges
    ad_password: "Password123!"
    github_url: "https://github.com/carlospolop/PEASS-ng/tree/master/winPEAS"

  tasks:
    - name: Install WINPEAS ns
      git:
        repo: "{{ github_url }}"
        dest: "."
    - name: Run Executable
        win_shell: "./winPEAS/winPEASps1/winPEAS.ps1"
    

    - name: Restart the machine
      win_reboot:
      when: ansible_reboot_pending | bool
